import type { Metadata } from 'next'
import Link from 'next/link'
import { type Locale } from '@/lib/i18n'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>
}): Promise<Metadata> {
  const { lang } = await params
  return {
    title: lang === 'es' ? 'Instrucciones de Eliminación de Datos de Usuario' : 'User Data Deletion Instructions',
    description:
      lang === 'es'
        ? 'Cómo solicitar la eliminación de sus datos de la plataforma NORA de Project NEED.'
        : 'How to request deletion of your data from the NORA AI Business Operating System by Project NEED.',
  }
}

const CONTACT_EMAIL = 'jeanpaulcocaleca@gmail.com'

export default async function DataDeletion({
  params,
}: {
  params: Promise<{ lang: string }>
}) {
  const { lang } = await params
  const es = lang === 'es'

  const deletionItems = es
    ? [
        { item: 'Información de cuenta y registro', desc: 'Nombre de empresa, datos de contacto, credenciales de cuenta' },
        { item: 'Credenciales de conexión de WhatsApp Business', desc: 'Tokens de API, asociaciones de números de teléfono, configuraciones de webhook' },
        { item: 'Registros operativos', desc: 'Órdenes de trabajo, tareas, registros de gastos, informes generados por NORA' },
        { item: 'Datos de procesamiento de mensajes', desc: 'Datos estructurados extraídos de sus conversaciones de WhatsApp' },
        { item: 'Memoria empresarial y conocimiento', desc: 'Conocimiento organizacional acumulado almacenado en la capa de memoria de NORA' },
        { item: 'Registros de personal y equipo', desc: 'Perfiles de empleados, roles y registros de comunicación dentro de NORA' },
      ]
    : [
        { item: 'Account and registration information', desc: 'Business name, contact details, account credentials' },
        { item: 'WhatsApp Business connection credentials', desc: 'API tokens, phone number associations, webhook configurations' },
        { item: 'Operational records', desc: 'Work orders, tasks, expense records, reports generated by NORA' },
        { item: 'Message processing data', desc: 'Structured data extracted from your WhatsApp conversations' },
        { item: 'Business memory and knowledge', desc: "Accumulated organizational knowledge stored in NORA's memory layer" },
        { item: 'Staff and team records', desc: 'Employee profiles, roles, and communication records within NORA' },
      ]

  const timeline = es
    ? [
        { days: '1–3 días', label: 'Confirmación de recepción', desc: 'Confirmaremos la recepción de su solicitud de eliminación por correo electrónico.' },
        { days: '30 días', label: 'Finalización', desc: 'Todos los datos solicitados serán eliminados dentro de los 30 días calendario posteriores a la confirmación de la solicitud.' },
        { days: 'Después', label: 'Confirmación final', desc: 'Le enviaremos un correo electrónico de confirmación final una vez que se complete la eliminación.' },
      ]
    : [
        { days: '1–3 days', label: 'Acknowledgement', desc: 'We will confirm receipt of your deletion request by email.' },
        { days: '30 days', label: 'Completion', desc: 'All requested data will be deleted within 30 calendar days of request confirmation.' },
        { days: 'After', label: 'Confirmation', desc: 'We will send a final confirmation email once deletion is complete.' },
      ]

  return (
    <div style={{ paddingTop: 'var(--nav-h)' }}>
      <div className="container">
        <div style={{ maxWidth: 720, margin: '0 auto', padding: '4rem 0 6rem' }}>
          <div style={{ marginBottom: '3rem', paddingBottom: '2rem', borderBottom: '1px solid var(--rim)' }}>
            <div className="eyebrow" style={{ marginBottom: '0.75rem' }}>Legal</div>
            <h1 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', marginBottom: '0.75rem' }}>
              {es ? 'Instrucciones de Eliminación de Datos de Usuario' : 'User Data Deletion Instructions'}
            </h1>
            <p style={{ color: 'var(--muted)', fontSize: '0.9375rem', margin: 0 }}>
              {es
                ? 'Cómo solicitar la eliminación de sus datos de la plataforma NORA.'
                : 'How to request the deletion of your data from the NORA platform.'}
            </p>
          </div>

          <div style={{
            background: 'var(--surface)', border: '1px solid var(--rim)',
            borderRadius: 'var(--r)', padding: '1.1rem 1.25rem',
            marginBottom: '2.5rem',
          }}>
            <p style={{ fontSize: '0.9375rem', color: 'var(--muted)', margin: 0, lineHeight: 1.7 }}>
              {es
                ? <><strong style={{ color: 'var(--fg)' }}>Nota importante:</strong> Desconectar su cuenta de WhatsApp Business de NORA y solicitar la eliminación de datos son acciones separadas. Desconectar su cuenta detendrá el procesamiento futuro de mensajes, pero los datos operativos históricos ya almacenados en NORA permanecerán hasta que envíe una solicitud de eliminación formal. Se requiere una solicitud de eliminación por escrito para eliminar los datos almacenados. Podemos solicitar que verifique su identidad y autorización antes de procesar una solicitud de eliminación para confirmar que tiene autoridad sobre la cuenta empresarial en cuestión.</>
                : <><strong style={{ color: 'var(--fg)' }}>Important note:</strong> Disconnecting your WhatsApp Business account from NORA and requesting data deletion are separate actions. Disconnecting your account stops future message processing, but historical operational data already stored in NORA will remain until you submit a formal deletion request. A written deletion request is required to remove stored data. We may ask you to verify your identity and authorization before processing a deletion request to confirm you have authority over the business account in question.</>}
            </p>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>

            {/* How to request */}
            <div>
              <h2 style={{ fontSize: '1.125rem', fontWeight: 600, letterSpacing: '-0.015em', marginBottom: '1rem', color: 'var(--fg)' }}>
                {es ? 'Cómo Solicitar la Eliminación de Datos' : 'How to Request Data Deletion'}
              </h2>
              <p style={{ color: 'var(--muted)', fontSize: '0.9375rem', lineHeight: 1.75, marginBottom: '1rem' }}>
                {es
                  ? 'Para solicitar la eliminación de sus datos de la plataforma NORA, contáctenos a través de cualquiera de los siguientes métodos:'
                  : 'To request the deletion of your data from the NORA platform, contact us using any of the following methods:'}
              </p>

              <div style={{
                background: 'var(--surface)', border: '1px solid var(--rim)',
                borderRadius: 'var(--r-lg)', padding: '1.5rem', marginBottom: '1rem',
              }}>
                <div style={{
                  fontFamily: 'var(--font-mono)', fontSize: '0.7rem',
                  letterSpacing: '0.1em', textTransform: 'uppercase',
                  color: 'var(--accent)', marginBottom: '0.75rem',
                }}>
                  {es ? 'Solicitud por Correo Electrónico' : 'Email Request'}
                </div>
                <p style={{ color: 'var(--muted)', fontSize: '0.9375rem', margin: '0 0 0.75rem' }}>
                  {es
                    ? <>Envíe un correo electrónico a{' '}
                      <a href={`mailto:${CONTACT_EMAIL}?subject=Solicitud de Eliminación de Datos — NORA`} style={{ color: 'var(--accent)' }}>
                        {CONTACT_EMAIL}
                      </a>{' '}
                      con el asunto <strong style={{ color: 'var(--fg)' }}>&quot;Solicitud de Eliminación de Datos — NORA&quot;</strong>.</>
                    : <>Send an email to{' '}
                      <a href={`mailto:${CONTACT_EMAIL}?subject=Data Deletion Request — NORA`} style={{ color: 'var(--accent)' }}>
                        {CONTACT_EMAIL}
                      </a>{' '}
                      with the subject line <strong style={{ color: 'var(--fg)' }}>&quot;Data Deletion Request — NORA&quot;</strong>.</>}
                </p>
                <p style={{ color: 'var(--muted)', fontSize: '0.875rem', margin: 0, lineHeight: 1.65 }}>
                  {es ? 'Por favor incluya en su correo:' : 'Please include in your email:'}
                </p>
                <ul style={{ color: 'var(--muted)', fontSize: '0.875rem', lineHeight: 1.75, marginTop: '0.5rem', paddingLeft: '1.25rem' }}>
                  {es ? <>
                    <li>El nombre de su empresa registrada en NORA</li>
                    <li>El número de teléfono de WhatsApp Business conectado a su cuenta</li>
                    <li>La dirección de correo electrónico asociada a su cuenta</li>
                    <li>Si desea eliminación parcial (tipos de datos específicos) o eliminación completa de la cuenta</li>
                  </> : <>
                    <li>Your business name registered with NORA</li>
                    <li>The WhatsApp Business phone number connected to your account</li>
                    <li>The email address associated with your account</li>
                    <li>Whether you want partial deletion (specific data types) or complete account deletion</li>
                  </>}
                </ul>
              </div>

              <div style={{ background: 'var(--raised)', border: '1px solid var(--rim)', borderRadius: 'var(--r)', padding: '1.25rem' }}>
                <div style={{ fontSize: '0.875rem', color: 'var(--muted)', lineHeight: 1.65 }}>
                  {es
                    ? <>También puede enviar su solicitud a través de nuestra{' '}
                      <Link href={`/${lang}/contact`} style={{ color: 'var(--accent)' }}>página de Contacto</Link>
                      {' '}— mencione "solicitud de eliminación de datos" en su mensaje.</>
                    : <>You may also submit your request through our{' '}
                      <Link href={`/${lang}/contact`} style={{ color: 'var(--accent)' }}>Contact page</Link>
                      {' '}— please mention &quot;data deletion request&quot; in your message.</>}
                </div>
              </div>
            </div>

            {/* What gets deleted */}
            <div>
              <h2 style={{ fontSize: '1.125rem', fontWeight: 600, letterSpacing: '-0.015em', marginBottom: '0.9rem', color: 'var(--fg)' }}>
                {es ? 'Qué Datos se Eliminan' : 'What Data Gets Deleted'}
              </h2>
              <p style={{ color: 'var(--muted)', fontSize: '0.9375rem', lineHeight: 1.75, marginBottom: '1rem' }}>
                {es
                  ? 'Una solicitud de eliminación completa de datos eliminará:'
                  : 'A complete data deletion request will remove:'}
              </p>
              <div style={{
                display: 'flex', flexDirection: 'column', gap: '0',
                background: 'var(--surface)', border: '1px solid var(--rim)',
                borderRadius: 'var(--r-lg)', overflow: 'hidden',
              }}>
                {deletionItems.map((row, i, arr) => (
                  <div
                    key={i}
                    style={{
                      display: 'flex', flexDirection: 'column', gap: '0.2rem',
                      padding: '0.9rem 1.1rem',
                      borderBottom: i < arr.length - 1 ? '1px solid var(--rim-faint)' : 'none',
                    }}
                  >
                    <div style={{ fontSize: '0.875rem', fontWeight: 500, color: 'var(--fg)' }}>✓ {row.item}</div>
                    <div style={{ fontSize: '0.8125rem', color: 'var(--muted)' }}>{row.desc}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Timeline */}
            <div>
              <h2 style={{ fontSize: '1.125rem', fontWeight: 600, letterSpacing: '-0.015em', marginBottom: '0.9rem', color: 'var(--fg)' }}>
                {es ? 'Plazos' : 'Timeline'}
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                {timeline.map(row => (
                  <div
                    key={row.label}
                    style={{
                      display: 'flex', gap: '1rem', alignItems: 'flex-start',
                      padding: '0.9rem 1.1rem',
                      background: 'var(--surface)', border: '1px solid var(--rim)',
                      borderRadius: 'var(--r)',
                    }}
                  >
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--accent)', minWidth: 80, paddingTop: '0.05rem' }}>
                      {row.days}
                    </div>
                    <div>
                      <div style={{ fontWeight: 500, fontSize: '0.875rem', color: 'var(--fg)', marginBottom: '0.2rem' }}>{row.label}</div>
                      <div style={{ fontSize: '0.8125rem', color: 'var(--muted)' }}>{row.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Exceptions */}
            <div>
              <h2 style={{ fontSize: '1.125rem', fontWeight: 600, letterSpacing: '-0.015em', marginBottom: '0.9rem', color: 'var(--fg)' }}>
                {es ? 'Excepciones' : 'Exceptions'}
              </h2>
              <p style={{ color: 'var(--muted)', fontSize: '0.9375rem', lineHeight: 1.75, margin: 0 }}>
                {es
                  ? 'Podemos conservar ciertos datos cuando la ley lo exija, para la prevención del fraude, para resolver disputas o para hacer cumplir nuestros acuerdos. Donde conservemos datos bajo una excepción legal, le notificaremos qué se conserva y por qué. No usaremos los datos conservados para ningún otro propósito.'
                  : 'We may retain certain data where required by law, for fraud prevention, to resolve disputes, or to enforce our agreements. Where we retain data under a legal exception, we will notify you of what is retained and why. We will not use retained data for any other purpose.'}
              </p>
            </div>

            {/* Questions */}
            <div style={{
              background: 'var(--accent-10)', border: '1px solid var(--accent-border)',
              borderRadius: 'var(--r)', padding: '1.25rem',
            }}>
              <p style={{ fontSize: '0.9375rem', color: 'var(--muted)', margin: 0, lineHeight: 1.65 }}>
                {es
                  ? <>¿Tiene preguntas sobre la eliminación de datos? Contáctenos en{' '}
                    <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: 'var(--accent)' }}>{CONTACT_EMAIL}</a>
                    . Normalmente respondemos en 2 días hábiles.</>
                  : <>Questions about data deletion? Contact us at{' '}
                    <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: 'var(--accent)' }}>{CONTACT_EMAIL}</a>
                    . We typically respond within 2 business days.</>}
              </p>
            </div>

          </div>

          <div style={{ marginTop: '3rem', paddingTop: '2rem', borderTop: '1px solid var(--rim)' }}>
            <Link href={`/${lang}`} style={{ color: 'var(--muted)', fontSize: '0.875rem' }}>
              ← {es ? 'Volver a neednora.com' : 'Back to neednora.com'}
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
